kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30080 # Exposes node port for Gateway
        hostPort: 8080
        protocol: TCP
      - containerPort: 30000 # Exposes node port for Grafana
        hostPort: 3000
        protocol: TCP
      - containerPort: 30090 # Exposes node port for Minio API
        hostPort: 9000
        protocol: TCP
      - containerPort: 30091 # Exposes node port for Minio Console
        hostPort: 9001
        protocol: TCP
      - containerPort: 30380 # Exposes node port for redis-ratelimit
        hostPort: 6380
        protocol: TCP
