apiVersion: v1
kind: ConfigMap
metadata:
  name: mini-lambda-config
  namespace: mini-lambda
data:
  LOG_LEVEL: "info"
  POSTGRES_HOST: "mini-lambda-postgres-prod.cv0egskwmy9k.ap-south-1.rds.amazonaws.com"
  POSTGRES_PORT: "5432"
  POSTGRES_USER: "postgres"
  POSTGRES_DB: "mini_lambda"
  POSTGRES_SSLMODE: "require"
  REDIS_CACHE_ADDR: "mini-lambda-redis.pbdkl2.0001.aps1.cache.amazonaws.com:6379"
  REDIS_RATELIMIT_ADDR: "mini-lambda-redis.pbdkl2.0001.aps1.cache.amazonaws.com:6379"
  RABBITMQ_URL: "${RABBITMQ_URL}"
  S3_ENDPOINT: ""
  S3_REGION: "ap-south-1"
  S3_BUCKET: "mini-lambda-storage-20260228134417281800000001"
  RATE_LIMIT_CAPACITY: "10000"
  RATE_LIMIT_REFILL_RATE: "5000"
  BUILD_SERVICE_URL: "http://build-master:8082"
  LAMBDA_SERVICE_URL: "http://lambda-service:8081"
