apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: mini-lambda
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      enableServiceLinks: false
      containers:
        - name: gateway
          image: ghcr.io/${GITHUB_USER}/gateway:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: mini-lambda-config
          env:
            - name: SERVICE_NAME
              value: "gateway"
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: mini-lambda
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080 # This matches the extraPortMappings in our kind-config
  selector:
    app: gateway
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gateway-ingress
  namespace: mini-lambda
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gateway
                port:
                  number: 8080
