apiVersion: v1
kind: Secret
metadata:
  name: mini-lambda-secrets
  namespace: mini-lambda
type: Opaque
stringData:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
  RABBITMQ_USER: "guest"
  RABBITMQ_PASS: "guest"
  MINIO_ROOT_USER: "minioadmin"
  MINIO_ROOT_PASSWORD: "minioadmin"
  GRAFANA_USER: "admin"
  GRAFANA_PASS: "admin"
